board = Board.new
board.mark_board(1, "B")
board.mark_board(2, "B")
board.mark_board(2, "B")
board.mark_board(3, "W")
board.mark_board(3, "W")
board.mark_board(3, "B")
board.mark_board(4, "W")
board.mark_board(4, "B")
board.mark_board(4, "W")
board.mark_board(4, "B")
board.mark_board(2, "W")
board.mark_board(1, "B")
board.mark_board(1, "W")
board.mark_board(1, "W")